FROM almalinux:latest

RUN dnf update -y --refresh

RUN dnf install -y dnf-plugins-core

RUN dnf config-manager --set-enabled crb

RUN dnf install -y gcc make autoconf automake libtool rpm-build kernel-rpm-macros libtirpc-devel libblkid-devel libuuid-devel libudev-devel openssl-devel zlib-devel libaio-devel libattr-devel elfutils-libelf-devel kernel-devel kernel-abi-stablelists python3 python3-devel python3-setuptools python3-cffi libffi-devel wget

RUN echo -e "\n%debug_package %{nil}" >> ~/.rpmmacros

WORKDIR /work

COPY entry.sh /

ENTRYPOINT ["/bin/bash", "/entry.sh"]