FROM fedora:37
RUN dnf update -y --refresh
RUN dnf install -y pandoc texlive-scheme-medium 'tex(wrapfig.sty)' 'tex(capt-of.sty)' \
'tex(beamerthememetropolis.sty)' 'tex(lastpage.sty)' 'tex(turnthepage.sty)'

WORKDIR /docs
ENV LANG C.UTF-8

ENTRYPOINT ["pdflatex"]