FROM fedora:42
RUN dnf update -y --refresh
RUN dnf install -y pandoc texlive-scheme-medium texlive-fira texlive-firamath 'tex(wrapfig.sty)' 'tex(capt-of.sty)' \
'tex(beamerthememetropolis.sty)' 'tex(lastpage.sty)' 'tex(turnthepage.sty)' 'tex(svg.sty)' \
'tex(tikz.sty)' 'tex(mwe.sty)' 'tex(cellspace.sty)'

WORKDIR /docs
ENV LANG C.UTF-8

ENTRYPOINT ["xelatex"]
