FROM rockylinux:9

RUN dnf install -y dnf-plugins-core
RUN dnf config-manager --set-enabled crb
RUN dnf config-manager --set-enabled devel
RUN dnf install -y epel-release
RUN dnf update -y --refresh

WORKDIR /root

RUN dnf install -y git rpm-build rpmdevtools libgccjit-devel lcms2-devel \
libtree-sitter-devel

RUN dnf builddep -y emacs

RUN rpmdev-setuptree
RUN echo -e "\n%debug_package %{nil}" >> ~/.rpmmacros

COPY build.sh /root

ENTRYPOINT /bin/bash
