FROM fedora:36
RUN dnf update -y --refresh
RUN dnf install -y dnf-plugins-core git rpm-build rpmdevtools libgccjit-devel lcms2-devel
RUN dnf builddep -y emacs

WORKDIR /root
RUN rpmdev-setuptree
COPY build.sh /root

ENTRYPOINT /bin/bash
